import React from 'react';
import { Plant } from '../../types';
import { Sparkles, Sun, Droplets, Wind } from 'lucide-react';

type AIRecommendationsProps = {
  plants: Plant[];
};

const AIRecommendations: React.FC<AIRecommendationsProps> = ({ plants }) => {
  // In a real app, these would be generated by an AI based on plant data
  const recommendations = [
    {
      id: 1,
      icon: <Droplets className="h-5 w-5 text-blue-500" />,
      title: 'Optimize Watering',
      description: 'Your Peace Lily shows signs of overwatering. Consider letting the soil dry more between waterings.',
    },
    {
      id: 2,
      icon: <Sun className="h-5 w-5 text-amber-500" />,
      title: 'Light Adjustment',
      description: 'Move your Fiddle Leaf Fig closer to a window as it needs more light for optimal growth.',
    },
    {
      id: 3,
      icon: <Wind className="h-5 w-5 text-teal-500" />,
      title: 'Humidity Control',
      description: 'Consider using a humidifier for your Monstera, especially during the drier months.',
    }
  ];

  return (
    <div className="bg-white rounded-xl shadow-sm">
      <div className="px-4 py-3 border-b border-gray-200 flex items-center">
        <Sparkles className="h-5 w-5 text-purple-500 mr-2" />
        <h3 className="text-lg font-semibold text-gray-800">AI Recommendations</h3>
      </div>
      <ul className="divide-y divide-gray-200">
        {recommendations.map(rec => (
          <li key={rec.id} className="px-4 py-3">
            <div className="flex items-center">
              <div className="flex-shrink-0 mr-3">
                {rec.icon}
              </div>
              <div>
                <h4 className="text-sm font-medium text-gray-800">{rec.title}</h4>
                <p className="text-xs text-gray-500 mt-1">{rec.description}</p>
              </div>
            </div>
          </li>
        ))}
      </ul>
      <div className="px-4 py-3 border-t border-gray-200">
        <button className="text-sm text-purple-600 font-medium hover:text-purple-700">
          Get more personalized recommendations
        </button>
      </div>
    </div>
  );
};

export default AIRecommendations;